import fs from 'node:fs';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js';
import { z } from 'zod';
import { repoMap, getFile, contextReport } from './tools.js';

function toResult(payload) {
  return { content: [{ type: 'text', text: JSON.stringify(payload, null, 2) }] };
}

function toError(message) {
  return { content: [{ type: 'text', text: message }], isError: true };
}

export async function startMcpServer() {
  const pkg = JSON.parse(fs.readFileSync(new URL('../../package.json', import.meta.url), 'utf8'));
  const server = new McpServer({ name: 'ai-readability', version: pkg.version });

  server.registerTool(
    'repo_map',
    {
      title: 'Repo Map',
      description: 'Returns the CONTEXT_MAP.md index of distilled file summaries for a repo (generated by `ai-readability distill --write`).',
      inputSchema: { root: z.string().optional() },
    },
    async ({ root }) => toResult(repoMap({ root })),
  );

  server.registerTool(
    'get_file',
    {
      title: 'Get File',
      description: "Returns a file's full source or distilled summary, given a path relative to root.",
      inputSchema: {
        root: z.string().optional(),
        path: z.string(),
        mode: z.enum(['summary', 'full']).optional(),
      },
    },
    async ({ root, path: filePath, mode }) => {
      try {
        return toResult(getFile({ root, path: filePath, mode }));
      } catch (err) {
        return toError(err.message);
      }
    },
  );

  server.registerTool(
    'context_report',
    {
      title: 'Context Report',
      description: 'Returns scoreRepo() JSON: token counts, grade, and per-file breakdown for a repo.',
      inputSchema: { root: z.string().optional(), respectGitignore: z.boolean().optional() },
    },
    async ({ root, respectGitignore }) => toResult(contextReport({ root, respectGitignore })),
  );

  const transport = new StdioServerTransport();
  await server.connect(transport);
}
